title: Anucha Saelee
description: Recent Mathematics graduate seeking practical industry experience to contribute to real-world AI and software projects while continuing to develop professionally.
logo: https://avatars.githubusercontent.com/u/186496505?v=4
show_downloads: false
theme: jekyll-theme-minimal
repository: anucha143/anucha143.github.io
url: https://anucha143.github.io
baseurl: ""

github:
  is_project_page: false
