title: Anucha Saelee
description: Recent Mathematics graduate seeking practical industry experience to contribute to real-world AI and software projects while continuing to develop professionally.
logo: https://avatars.githubusercontent.com/u/186496505?v=4
show_downloads: false
theme: jekyll-theme-minimal
repository: shiniji123/anucha.sae.work.github.io
url: https://shiniji123.github.io
baseurl: /anucha.sae.work.github.io

github:
  is_project_page: false
